### ISSUE TITLE
doctests are erroring but still passing CI

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/SparseArrays.jl#2]
Doctests are erroring for what looks like a missing `using SparseArrays` or something similar.

https://github.com/JuliaLang/SparseArrays.jl/runs/4132979600?check_suite_focus=true

However, it is still giving a green.

**Comment by DilumAluthge** [comment]
When you build the docs, doctest failures will never actually fail the build unless you pass the `strict=true` kwarg to the `Documenter.makedocs` function.

Alternatively, you can explicitly call the `Documenter.doctest` function, which will throw an error if the doctests fail.
