### ISSUE TITLE
SparseMatrixCSR should be a type alias for Transpose{SparseMatrixCSC}

### ISSUE THREAD

**Issue by ndinsmore** [JuliaLang/SparseArrays.jl#41]
I am surprised that this isn't already in SparseArray, but should we define:
`const SparseMatrixCSR{Tv,Ti} = Transpose{Tv,SparseMatrix{Tv,Ti}} where {Tv, Ti <: Integer}`

This plus a few simple additional methods would make it so Julia had psuedo built in support for compressed sparse matrixes.   

I am already using a definition like this and I can't believe that I am the only one.

If people agree I can take a shot at the PR.

**Comment by ViralBShah** [comment]
I think this can easily be experimented with in a package called `SparseMatrixCSR.jl`.
