### ISSUE TITLE
Make length(A.nzval)==nnz(A)

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/SparseArrays.jl#44]
We currently allow that `length(A.nzval)>nnz(A)` such that memory for future elements in the matrix can be preallocated. Instead `nnz(A)=A.colptr[n+1]-1`. However, as pointed out in https://github.com/JuliaLang/julia/pull/30435#issuecomment-452489492, this could simply be handled by `sizehint!` and having two different mechanisms for ensuring extras allocations seems superfluous. Hence, it might be worth simplifying the sparse matrix code and enforce that `nnz(A)==length(A.nzval)`.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/40523 I think
